"""Default seed data for Zoho Books Clone"""
from datetime import datetime, timedelta

def get_initial_seed_items():
    now = datetime.utcnow()
    return [
        {
            "id": "item-101",
            "name": 'Dell UltraSharp 27" 4K Monitor',
            "type": "goods",
            "sku": "MON-DELL-4K27",
            "unit": "pcs",
            "description": "4K IPS Monitor with USB-C Hub for workstation setups",
            "imageUrl": "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=400&q=80",
            "salesInfo": {
                "sellingPrice": 38500.0,
                "salesAccount": "Sales - Hardware",
                "description": "Standard client price for Dell 4K display",
            },
            "purchaseInfo": {
                "costPrice": 29000.0,
                "costAccount": "Cost of Goods Sold",
                "description": "Vendor cost from Dell Authorized Distributor",
                "preferredVendor": "TechDistro India Pvt Ltd",
            },
            "inventoryInfo": {
                "trackInventory": True,
                "openingStock": 25.0,
                "openingStockRate": 29000.0,
                "reorderLevel": 5.0,
                "warehouseLocation": "Main Warehouse - Shelf A3",
            },
            "createdAt": (now - timedelta(days=30)).isoformat() + "Z",
            "updatedAt": (now - timedelta(days=2)).isoformat() + "Z",
        },
        {
            "id": "item-102",
            "name": "Ergonomic Mesh Office Chair",
            "type": "goods",
            "sku": "FUR-CHR-ERG01",
            "unit": "pcs",
            "description": "High-back ergonomic mesh chair with adjustable lumbar support",
            "imageUrl": "https://images.unsplash.com/photo-1580481072645-022f9a6d1270?w=400&q=80",
            "salesInfo": {
                "sellingPrice": 14500.0,
                "salesAccount": "Sales - Office Supplies",
                "description": "Office furniture sales item",
            },
            "purchaseInfo": {
                "costPrice": 9200.0,
                "costAccount": "Cost of Goods Sold",
                "description": "Wholesale furniture procurement",
                "preferredVendor": "Urban Space Supplies",
            },
            "inventoryInfo": {
                "trackInventory": True,
                "openingStock": 12.0,
                "openingStockRate": 9200.0,
                "reorderLevel": 3.0,
                "warehouseLocation": "Main Warehouse - Bay B",
            },
            "createdAt": (now - timedelta(days=20)).isoformat() + "Z",
            "updatedAt": (now - timedelta(days=5)).isoformat() + "Z",
        },
        {
            "id": "item-103",
            "name": "Custom Web Application Development",
            "type": "service",
            "sku": "SRV-WEB-DEV",
            "unit": "hrs",
            "description": "Professional full-stack software development per hour",
            "imageUrl": None,
            "salesInfo": {
                "sellingPrice": 2500.0,
                "salesAccount": "Service Revenue",
                "description": "Hourly rate for custom enterprise web development",
            },
            "purchaseInfo": {
                "costPrice": 1200.0,
                "costAccount": "Subcontractor Costs",
                "description": "Internal developer billable cost rate",
                "preferredVendor": None,
            },
            "inventoryInfo": None,
            "createdAt": (now - timedelta(days=15)).isoformat() + "Z",
            "updatedAt": (now - timedelta(days=1)).isoformat() + "Z",
        },
        {
            "id": "item-104",
            "name": "Logitech MX Master 3S Wireless Mouse",
            "type": "goods",
            "sku": "ACC-LOG-MX3S",
            "unit": "pcs",
            "description": "Performance wireless mouse with 8K DPI sensor",
            "imageUrl": "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=400&q=80",
            "salesInfo": {
                "sellingPrice": 8995.0,
                "salesAccount": "Sales - Accessories",
                "description": "Logitech peripheral retail",
            },
            "purchaseInfo": {
                "costPrice": 6400.0,
                "costAccount": "Cost of Goods Sold",
                "description": "Direct distributor supply",
                "preferredVendor": "LogiDirect Traders",
            },
            "inventoryInfo": {
                "trackInventory": True,
                "openingStock": 4.0,
                "openingStockRate": 6400.0,
                "reorderLevel": 10.0,
                "warehouseLocation": "Main Warehouse - Drawer C1",
            },
            "createdAt": (now - timedelta(days=10)).isoformat() + "Z",
            "updatedAt": (now - timedelta(days=3)).isoformat() + "Z",
        },
        {
            "id": "item-105",
            "name": "Annual Accounting & Tax Audit Service",
            "type": "service",
            "sku": "SRV-TAX-AUDIT",
            "unit": "project",
            "description": "Comprehensive financial statements audit and tax filing advisory",
            "imageUrl": None,
            "salesInfo": {
                "sellingPrice": 75000.0,
                "salesAccount": "Consulting Revenue",
                "description": "Fixed audit retainer fee",
            },
            "purchaseInfo": {
                "costPrice": 40000.0,
                "costAccount": "Professional Fees",
                "description": "Chartered Accountant partner payout",
                "preferredVendor": None,
            },
            "inventoryInfo": None,
            "createdAt": (now - timedelta(days=5)).isoformat() + "Z",
            "updatedAt": (now - timedelta(days=1)).isoformat() + "Z",
        },
    ]
