"""add_payments_and_financial_tables

Revision ID: 9f391213a8bf
Revises: 3ffd02d46df9
Create Date: 2026-09-08 16:49:15.103662
"""
from __future__ import annotations

import sqlalchemy as sa

from alembic import op

revision = '9f391213a8bf'
down_revision = '3ffd02d46df9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=True),
    sa.Column('event_id', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_events_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_events_event_id'), ['event_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_payment_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_events_organization_id'), ['organization_id'], unique=False)

    op.create_table('financial_transactions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('transaction_id', sa.String(length=64), nullable=False),
    sa.Column('transaction_type', sa.String(length=40), nullable=False),
    sa.Column('reference_type', sa.String(length=40), nullable=False),
    sa.Column('reference_id', sa.String(length=64), nullable=True),
    sa.Column('debit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('credit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('account', sa.String(length=120), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('financial_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_financial_transactions_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_transactions_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_transactions_reference_id'), ['reference_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_transactions_transaction_id'), ['transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_transactions_transaction_type'), ['transaction_type'], unique=False)

    op.create_table('reconciliation_records',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('reconciliation_date', sa.Date(), nullable=False),
    sa.Column('settlement_id', sa.String(length=64), nullable=True),
    sa.Column('internal_payment_id', sa.String(length=32), nullable=True),
    sa.Column('razorpay_payment_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('discrepancy_note', sa.Text(), nullable=True),
    sa.Column('amount_expected', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('amount_actual', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('difference', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_by', sa.String(length=32), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reconciliation_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reconciliation_records_internal_payment_id'), ['internal_payment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reconciliation_records_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reconciliation_records_razorpay_payment_id'), ['razorpay_payment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reconciliation_records_reconciliation_date'), ['reconciliation_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_reconciliation_records_settlement_id'), ['settlement_id'], unique=False)

    op.create_table('settlements',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('settlement_id', sa.String(length=64), nullable=False),
    sa.Column('settlement_date', sa.Date(), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('fee_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('adjustments', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('refunds', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('bank_reference', sa.String(length=100), nullable=True),
    sa.Column('reconciled', sa.Boolean(), nullable=False),
    sa.Column('reconciled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('settlements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_settlements_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_settlements_settlement_date'), ['settlement_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_settlements_settlement_id'), ['settlement_id'], unique=True)

    op.create_table('external_payments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('external_transaction_id', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('payer_name', sa.String(length=120), nullable=True),
    sa.Column('payer_email', sa.String(length=120), nullable=True),
    sa.Column('payer_phone', sa.String(length=40), nullable=True),
    sa.Column('invoice_id', sa.String(length=32), nullable=True),
    sa.Column('customer_id', sa.String(length=32), nullable=True),
    sa.Column('bank_account_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('approval_token', sa.String(length=64), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('approval_notes', sa.Text(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.String(length=120), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('customer_payment_id', sa.String(length=32), nullable=True),
    sa.Column('raw_payload', sa.Text(), nullable=True),
    sa.Column('confirmation_email_sent', sa.Boolean(), nullable=False),
    sa.Column('confirmation_email_recipient', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['customer_payment_id'], ['customer_payments.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('external_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_external_payments_approval_token'), ['approval_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_external_payments_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_external_payments_customer_payment_id'), ['customer_payment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_external_payments_external_transaction_id'), ['external_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_external_payments_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_external_payments_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_external_payments_platform'), ['platform'], unique=False)
        batch_op.create_index(batch_op.f('ix_external_payments_status'), ['status'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('razorpay_order_id', sa.String(length=64), nullable=True),
    sa.Column('razorpay_payment_id', sa.String(length=64), nullable=False),
    sa.Column('razorpay_signature', sa.String(length=255), nullable=True),
    sa.Column('customer_id', sa.String(length=32), nullable=True),
    sa.Column('sales_order_id', sa.String(length=64), nullable=True),
    sa.Column('invoice_id', sa.String(length=32), nullable=True),
    sa.Column('customer_payment_id', sa.String(length=32), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('payment_method', sa.String(length=40), nullable=False),
    sa.Column('payment_status', sa.String(length=30), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refund_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('razorpay_fee', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tax_on_fee', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('net_settlement', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('settlement_id', sa.String(length=64), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_description', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['customer_payment_id'], ['customer_payments.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_customer_payment_id'), ['customer_payment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_payment_status'), ['payment_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_razorpay_order_id'), ['razorpay_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_razorpay_payment_id'), ['razorpay_payment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_sales_order_id'), ['sales_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_settlement_id'), ['settlement_id'], unique=False)

    op.create_table('refunds',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('payment_id', sa.String(length=32), nullable=False),
    sa.Column('razorpay_payment_id', sa.String(length=64), nullable=False),
    sa.Column('razorpay_refund_id', sa.String(length=64), nullable=False),
    sa.Column('invoice_id', sa.String(length=32), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('refund_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('speed', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refunds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refunds_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_refunds_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_refunds_payment_id'), ['payment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_refunds_razorpay_payment_id'), ['razorpay_payment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_refunds_razorpay_refund_id'), ['razorpay_refund_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_refunds_refund_date'), ['refund_date'], unique=False)

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=60), nullable=False))
        batch_op.add_column(sa.Column('payment_method', sa.String(length=40), nullable=False))
        batch_op.add_column(sa.Column('receipt_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('receipt_url')
        batch_op.drop_column('payment_method')
        batch_op.drop_column('category')

    with op.batch_alter_table('refunds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refunds_refund_date'))
        batch_op.drop_index(batch_op.f('ix_refunds_razorpay_refund_id'))
        batch_op.drop_index(batch_op.f('ix_refunds_razorpay_payment_id'))
        batch_op.drop_index(batch_op.f('ix_refunds_payment_id'))
        batch_op.drop_index(batch_op.f('ix_refunds_organization_id'))
        batch_op.drop_index(batch_op.f('ix_refunds_invoice_id'))

    op.drop_table('refunds')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_settlement_id'))
        batch_op.drop_index(batch_op.f('ix_payments_sales_order_id'))
        batch_op.drop_index(batch_op.f('ix_payments_razorpay_payment_id'))
        batch_op.drop_index(batch_op.f('ix_payments_razorpay_order_id'))
        batch_op.drop_index(batch_op.f('ix_payments_payment_status'))
        batch_op.drop_index(batch_op.f('ix_payments_organization_id'))
        batch_op.drop_index(batch_op.f('ix_payments_invoice_id'))
        batch_op.drop_index(batch_op.f('ix_payments_customer_payment_id'))
        batch_op.drop_index(batch_op.f('ix_payments_customer_id'))

    op.drop_table('payments')
    with op.batch_alter_table('external_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_external_payments_status'))
        batch_op.drop_index(batch_op.f('ix_external_payments_platform'))
        batch_op.drop_index(batch_op.f('ix_external_payments_organization_id'))
        batch_op.drop_index(batch_op.f('ix_external_payments_invoice_id'))
        batch_op.drop_index(batch_op.f('ix_external_payments_external_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_external_payments_customer_payment_id'))
        batch_op.drop_index(batch_op.f('ix_external_payments_customer_id'))
        batch_op.drop_index(batch_op.f('ix_external_payments_approval_token'))

    op.drop_table('external_payments')
    with op.batch_alter_table('settlements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_settlements_settlement_id'))
        batch_op.drop_index(batch_op.f('ix_settlements_settlement_date'))
        batch_op.drop_index(batch_op.f('ix_settlements_organization_id'))

    op.drop_table('settlements')
    with op.batch_alter_table('reconciliation_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reconciliation_records_settlement_id'))
        batch_op.drop_index(batch_op.f('ix_reconciliation_records_reconciliation_date'))
        batch_op.drop_index(batch_op.f('ix_reconciliation_records_razorpay_payment_id'))
        batch_op.drop_index(batch_op.f('ix_reconciliation_records_organization_id'))
        batch_op.drop_index(batch_op.f('ix_reconciliation_records_internal_payment_id'))

    op.drop_table('reconciliation_records')
    with op.batch_alter_table('financial_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_financial_transactions_transaction_type'))
        batch_op.drop_index(batch_op.f('ix_financial_transactions_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_financial_transactions_reference_id'))
        batch_op.drop_index(batch_op.f('ix_financial_transactions_organization_id'))
        batch_op.drop_index(batch_op.f('ix_financial_transactions_date'))

    op.drop_table('financial_transactions')
    with op.batch_alter_table('payment_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_events_organization_id'))
        batch_op.drop_index(batch_op.f('ix_payment_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_payment_events_event_id'))
        batch_op.drop_index(batch_op.f('ix_payment_events_entity_id'))

    op.drop_table('payment_events')
    # ### end Alembic commands ###
